services:
  db:
    image: mongo
    volumes:
      - data:/data/db
    container_name: db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:80"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Mount the entire frontend folder to /app
      - /app/node_modules 


volumes:
  data:
  logs: