apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksapp-deployment
  labels:
    app: tasksapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksapp
  template:
    metadata:
      labels:
        app: tasksapp
    spec:
      containers:
      - name: tasksapp
        image: tamal008/tasksapp:03
        env:
        - name: AUTH_ADDRESS
          value: "authapp-service.default"
        - name: TASKS_FOLDER
          value: "tasks"
